import { TalkingHead } from 'https://cdn.jsdelivr.net/npm/@met4citizen/talkinghead@1.7/+esm';
import { HeadTTS } from 'https://cdn.jsdelivr.net/npm/@met4citizen/headtts@1.3/+esm';

const AVATARS={
  female:{url:'https://huggingface.co/spaces/victor/gemma-avatar/resolve/main/public/avatars/brunette.glb',body:'F',voice:'af_bella',label:'Tutora de IA'},
  male:{url:'https://huggingface.co/wmghf2023/3d-figure-app-assets/resolve/main/rpm_fullbody.glb',body:'M',voice:'am_adam',label:'Tutor de IA'}
};
const $=id=>document.getElementById(id);
let head=null,headtts=null,recognition=null,messages=[];let mode='english';
let profile=JSON.parse(localStorage.getItem('maya-profile')||'{"gender":"female","name":"Maya"}');
function state(t,c=''){ $('state').textContent=t;document.body.className=c; }
function applyProfile(){const a=AVATARS[profile.gender];$('avatarName').textContent=profile.name;$('avatarRole').textContent=a.label;document.title=`${profile.name} — Zeuvastec`;}
function addMessage(who,text){const d=document.createElement('div');d.className='m';d.innerHTML=`<span class="who">${who}</span>${escapeHtml(text)}`;$('messages').appendChild(d);$('messages').scrollTop=$('messages').scrollHeight;}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function initAvatar(){const a=AVATARS[profile.gender];$('loading').style.display='block';head=new TalkingHead($('tutor-3d-avatar'),{ttsEndpoint:'N/A',lipsyncModules:[],cameraView:'upper',cameraDistance:0,cameraZoomEnable:false,cameraPanEnable:false,cameraRotateEnable:false,modelFPS:60,modelPixelRatio:1,avatarIdleEyeContact:.78,avatarSpeakingEyeContact:.92,avatarListeningEyeContact:.82,avatarSpeakingHeadMove:.7,avatarListeningHeadMove:.45,avatarMood:'neutral',lightAmbientIntensity:1.05,lightDirectIntensity:1.15,lightSpotIntensity:.5,lightAmbientColor:0xffffff,lightDirectColor:0xffffff,lightSpotColor:0xffffff});await head.showAvatar({url:a.url,body:a.body,avatarMood:'neutral',lipsyncLang:'en'},ev=>{if(ev?.lengthComputable)$('loading').textContent=`Carregando Avatar 3D… ${Math.round(ev.loaded/ev.total*100)}%`;});head.setView('upper',{cameraDistance:0,cameraX:0,cameraY:.02,cameraRotateX:0,cameraRotateY:0});$('loading').style.display='none';state('Pronto para conversar');}
async function initTTS(){const a=AVATARS[profile.gender];headtts=new HeadTTS({endpoints:['webgpu','wasm'],languages:['en-us'],voices:['af_bella','am_adam'],audioCtx:head.audioCtx,workerModule:'https://cdn.jsdelivr.net/npm/@met4citizen/headtts@1.3/modules/worker-tts.mjs',dictionaryURL:'https://cdn.jsdelivr.net/npm/@met4citizen/headtts@1.3/dictionaries/',trace:0});headtts.onstart=()=>state(`${profile.name} está falando`,'speaking');headtts.onmessage=m=>{if(m.type==='audio')head.speakAudio(m.data,{isRaw:true},()=>{});};await headtts.connect();await headtts.setup({voice:a.voice,language:'en-us',speed:1.03,audioEncoding:'wav'});}
async function speak(text){if(!text||!headtts)return;state(`${profile.name} está falando`,'speaking');try{headtts.synthesize({input:text.slice(0,700)});}catch(e){console.error(e);state('Pronto para conversar');}}
async function ask(text){text=text.trim();if(!text)return;$('textInput').value='';addMessage('Você',text);state(`${profile.name} está pensando…`);messages.push({role:'user',content:text});try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages,name:profile.name,gender:profile.gender,language:mode==='english'?'en-US':'pt-BR'})});const data=await r.json();if(!r.ok)throw new Error(data?.error||`Erro ${r.status}`);messages.push({role:'assistant',content:data.text});addMessage(profile.name,data.text);await speak(data.text);}catch(e){console.error(e);addMessage(profile.name,`Erro: ${e.message}`);state('Verifique a conexão com o GPT');}}
function setupRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('micBtn').onclick=()=>{$('textInput').focus();};return;}recognition=new SR();recognition.continuous=false;recognition.interimResults=false;recognition.lang='en-US';recognition.onstart=()=>state('Estou ouvindo…','listening');recognition.onresult=e=>ask(e.results?.[0]?.[0]?.transcript||'');recognition.onerror=()=>state('Pronto para conversar');recognition.onend=()=>{if(document.body.classList.contains('listening'))state('Pronto para conversar');};}
function openProfile(){$('profile').classList.remove('hidden');document.querySelectorAll('.avatar-option').forEach(b=>b.classList.toggle('selected',b.dataset.gender===profile.gender));$('profileName').value=profile.name;}
async function saveProfile(){const name=$('profileName').value.trim().replace(/\s+/g,' ');if(name.length<2){$('profileStatus').textContent='Digite um nome com pelo menos 2 caracteres.';return;}const gender=document.querySelector('.avatar-option.selected')?.dataset.gender||'female';profile={gender,name:name.slice(0,24)};localStorage.setItem('maya-profile',JSON.stringify(profile));$('profile').classList.add('hidden');applyProfile();location.reload();}
async function checkServer(){const el=$('settingsStatus');el.textContent='Testando…';try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:'Responda apenas: OK'}],name:profile.name,gender:profile.gender,language:'pt-BR'})});const d=await r.json();if(!r.ok)throw new Error(d?.error||`HTTP ${r.status}`);$('serverStatus').className='ok';$('serverStatus').textContent=`Servidor conectado. Modelo: ${d.model||'configurado'}`;el.textContent='Conexão com GPT funcionando.';}catch(e){$('serverStatus').className='bad';$('serverStatus').textContent=e.message;el.textContent='Corrija a variável OPENAI_API_KEY na Vercel.';}}
$('micBtn').onclick=()=>{if(!recognition){$('textInput').focus();return;}try{recognition.lang=mode==='english'?'en-US':'pt-BR';recognition.start();}catch{}};$('sendBtn').onclick=()=>ask($('textInput').value);$('textInput').addEventListener('keydown',e=>{if(e.key==='Enter')ask($('textInput').value)});$('profileBtn').onclick=openProfile;$('closeProfile').onclick=()=>$('profile').classList.add('hidden');$('saveProfile').onclick=saveProfile;$('settingsBtn').onclick=()=>{$('settings').classList.remove('hidden');checkServer();};$('closeSettings').onclick=()=>$('settings').classList.add('hidden');$('checkServer').onclick=checkServer;$('englishBtn').onclick=()=>{mode='english';$('englishBtn').classList.add('active');$('chatBtn').classList.remove('active');};$('chatBtn').onclick=()=>{mode='chat';$('chatBtn').classList.add('active');$('englishBtn').classList.remove('active');};document.querySelectorAll('.avatar-option').forEach(b=>b.onclick=()=>{document.querySelectorAll('.avatar-option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');});
window.addEventListener('DOMContentLoaded',async()=>{applyProfile();setupRecognition();try{await initAvatar();await initTTS();addMessage(profile.name,`Hello! I'm ${profile.name}. Let's practice English together.`);await speak(`Hello! I'm ${profile.name}. Let's practice English together.`);}catch(e){console.error(e);$('loading').textContent='Falha ao carregar o Avatar 3D';state('Verifique a conexão com a internet');}});
